/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as LangIndexRouteImport } from './app/$lang/index'
import { Route as LangPrivacyRouteImport } from './app/$lang/privacy'

const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/$lang/privacy',
  path: '/$lang/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$lang/privacy' | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$lang/privacy' | '/$lang'
  id: '__root__' | '/$lang/privacy' | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangIndexRoute: typeof LangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/$lang/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LangPrivacyRoute: LangPrivacyRoute,
  LangIndexRoute: LangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
